import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'; // your custom file

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Saad Mukhtar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
        {/* Bootstrap 5.3 CSS */}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
        {/* Font Awesome for icons */}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
        {/* Custom CSS */}
        {/* <link rel="stylesheet" href="/assets/css/style.css" /> */}
        {/* Favicon */}
        <link rel="icon" href="/assets/images/favicon.png" type="image/png" />
    



      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        
        {/* Bootstrap 5.3 JS Bundle with Popper */}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" async></script>
      </body>
    </html>
  );
}
